// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PingCRM.Data;

#nullable disable

namespace PingCRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250921031450_InitialCreateWithSeedData")]
    partial class InitialCreateWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PingCRM.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Name = "Acme Corporation",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        });
                });

            modelBuilder.Entity("PingCRM.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("OrganizationId");

                    b.ToTable("contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Address = "123 Tech Street",
                            City = "San Francisco",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "sarah.johnson@techsolutions.com",
                            FirstName = "Sarah",
                            LastName = "Johnson",
                            OrganizationId = 1,
                            Phone = "+1 555-0111",
                            PostalCode = "94105",
                            Region = "CA",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            Address = "123 Tech Street",
                            City = "San Francisco",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "michael.chen@techsolutions.com",
                            FirstName = "Michael",
                            LastName = "Chen",
                            OrganizationId = 1,
                            Phone = "+1 555-0222",
                            PostalCode = "94105",
                            Region = "CA",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 1,
                            Address = "456 Marketing Avenue",
                            City = "New York",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "emily.rodriguez@globalmarketing.com",
                            FirstName = "Emily",
                            LastName = "Rodriguez",
                            OrganizationId = 2,
                            Phone = "+1 555-0333",
                            PostalCode = "10001",
                            Region = "NY",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 1,
                            Address = "789 Creative Lane",
                            City = "Los Angeles",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "david.wilson@designstudio.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            OrganizationId = 3,
                            Phone = "+1 555-0444",
                            PostalCode = "90210",
                            Region = "CA",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 1,
                            Address = "321 Business Plaza",
                            City = "Chicago",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "lisa.anderson@consulting.com",
                            FirstName = "Lisa",
                            LastName = "Anderson",
                            OrganizationId = 4,
                            Phone = "+1 555-0555",
                            PostalCode = "60601",
                            Region = "IL",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 1,
                            Address = "654 Innovation Drive",
                            City = "Austin",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "robert.taylor@innovationlabs.com",
                            FirstName = "Robert",
                            LastName = "Taylor",
                            OrganizationId = 5,
                            Phone = "+1 555-0666",
                            PostalCode = "73301",
                            Region = "TX",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 1,
                            Address = "987 Independent Way",
                            City = "Seattle",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "jennifer.brown@freelancer.com",
                            FirstName = "Jennifer",
                            LastName = "Brown",
                            Phone = "+1 555-0777",
                            PostalCode = "98101",
                            Region = "WA",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 1,
                            Address = "147 Solo Street",
                            City = "Denver",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "james.miller@consultant.com",
                            FirstName = "James",
                            LastName = "Miller",
                            Phone = "+1 555-0888",
                            PostalCode = "80201",
                            Region = "CO",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        });
                });

            modelBuilder.Entity("PingCRM.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DeletedAt");

                    b.ToTable("organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Address = "123 Tech Street",
                            City = "San Francisco",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "info@techsolutions.com",
                            Name = "Tech Solutions Inc",
                            Phone = "+1 555-0123",
                            PostalCode = "94105",
                            Region = "CA",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            Address = "456 Marketing Avenue",
                            City = "New York",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "contact@globalmarketing.com",
                            Name = "Global Marketing Group",
                            Phone = "+1 555-0456",
                            PostalCode = "10001",
                            Region = "NY",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 1,
                            Address = "789 Creative Lane",
                            City = "Los Angeles",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "hello@designstudio.com",
                            Name = "Design Studio Pro",
                            Phone = "+1 555-0789",
                            PostalCode = "90210",
                            Region = "CA",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 1,
                            Address = "321 Business Plaza",
                            City = "Chicago",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "info@consulting.com",
                            Name = "Consulting Partners Ltd",
                            Phone = "+1 555-0321",
                            PostalCode = "60601",
                            Region = "IL",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 1,
                            Address = "654 Innovation Drive",
                            City = "Austin",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "contact@innovationlabs.com",
                            Name = "Innovation Labs",
                            Phone = "+1 555-0654",
                            PostalCode = "73301",
                            Region = "TX",
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920)
                        });
                });

            modelBuilder.Entity("PingCRM.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Owner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            AccountId = 1,
                            ConcurrencyStamp = "42895ece-88b6-4d3d-9988-09268e2643be",
                            CreatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            Email = "johndoe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHNDOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHNDOE@EXAMPLE.COM",
                            Owner = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEHX8mn9KpQW0LYwv4eoXBlhnigj96588XQmJk7Q9NynzPh5kYUPbKWl0iRrPvgYT6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e017e40-531e-4bfd-9746-f2ec5ab998c6",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2025, 9, 21, 3, 14, 49, 780, DateTimeKind.Utc).AddTicks(9920),
                            UserName = "johndoe@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PingCRM.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PingCRM.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PingCRM.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PingCRM.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PingCRM.Models.Contact", b =>
                {
                    b.HasOne("PingCRM.Models.Account", "Account")
                        .WithMany("Contacts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PingCRM.Models.Organization", "Organization")
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PingCRM.Models.Organization", b =>
                {
                    b.HasOne("PingCRM.Models.Account", "Account")
                        .WithMany("Organizations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PingCRM.Models.User", b =>
                {
                    b.HasOne("PingCRM.Models.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PingCRM.Models.Account", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Organizations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PingCRM.Models.Organization", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
